name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: npm install
              run: npm ci
            - name: run the unit tests
              run: npm test
            - name: Build and push the image
              run: |
                docker login --username mysoladi --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/mysoladi/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/mysoladi/arithmetic-service:latest
            - name: Publish the image to azure container registry
              run: |
                docker login --username practicumcrrr --password ${{secrets.CONTAINER_REGISTRY}} practicumcrrr.azurecr.io
                docker tag ghcr.io/mysoladi/arithmetic-service:latest   practicumcrrr.azurecr.io/arithmetic-service:1
                docker push practicumcrrr.azurecr.io/arithmetic-service:1